package persistance.entities;
// Generated 11 nov. 2017 15:09:43 by Hibernate Tools 3.4.0.CR1


import java.util.HashSet;
import java.util.Set;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Hotel generated by hbm2java
 */
@Entity
@Table(name="hotel"
    ,catalog="agence"
)
public class Hotel  implements java.io.Serializable {


     private int idHotel;
     private String nom;
     private String adresse;
     private Integer tel;
     private Set<Reservation> reservations = new HashSet<Reservation>(0);

    public Hotel() {
    }

	
    public Hotel(int idHotel, String nom) {
        this.idHotel = idHotel;
        this.nom = nom;
    }
    public Hotel(int idHotel, String nom, String adresse, Integer tel, Set<Reservation> reservations) {
       this.idHotel = idHotel;
       this.nom = nom;
       this.adresse = adresse;
       this.tel = tel;
       this.reservations = reservations;
    }
   
     @Id 

    
    @Column(name="idHotel", unique=true, nullable=false)
    public int getIdHotel() {
        return this.idHotel;
    }
    
    public void setIdHotel(int idHotel) {
        this.idHotel = idHotel;
    }

    
    @Column(name="nom", nullable=false)
    public String getNom() {
        return this.nom;
    }
    
    public void setNom(String nom) {
        this.nom = nom;
    }

    
    @Column(name="adresse")
    public String getAdresse() {
        return this.adresse;
    }
    
    public void setAdresse(String adresse) {
        this.adresse = adresse;
    }

    
    @Column(name="tel")
    public Integer getTel() {
        return this.tel;
    }
    
    public void setTel(Integer tel) {
        this.tel = tel;
    }

@OneToMany(fetch=FetchType.LAZY, mappedBy="hotel")
    public Set<Reservation> getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set<Reservation> reservations) {
        this.reservations = reservations;
    }




}


