package persistance.entities;
// Generated 11 nov. 2017 15:09:43 by Hibernate Tools 3.4.0.CR1


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Reservation generated by hbm2java
 */
@Entity
@Table(name="reservation"
    ,catalog="agence"
)
public class Reservation  implements java.io.Serializable {


     private int idReser;
     private Client client=new Client();
     private Hotel hotel=new Hotel();
     private Date dateResr;
     private Integer nbNuits;

    public Reservation() {
    }

	
    public Reservation(int idReser, Client client, Hotel hotel) {
        this.idReser = idReser;
        this.client = client;
        this.hotel = hotel;
    }
    public Reservation(int idReser, Client client, Hotel hotel, Date dateResr, Integer nbNuits) {
       this.idReser = idReser;
       this.client = client;
       this.hotel = hotel;
       this.dateResr = dateResr;
       this.nbNuits = nbNuits;
    }
   
     @Id 

    
    @Column(name="idReser", unique=true, nullable=false)
    public int getIdReser() {
        return this.idReser;
    }
    
    public void setIdReser(int idReser) {
        this.idReser = idReser;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idClient", nullable=false)
    public Client getClient() {
        return this.client;
    }
    
    public void setClient(Client client) {
        this.client = client;
    }

@ManyToOne(fetch=FetchType.LAZY)
    @JoinColumn(name="idHotel", nullable=false)
    public Hotel getHotel() {
        return this.hotel;
    }
    
    public void setHotel(Hotel hotel) {
        this.hotel = hotel;
    }

    @Temporal(TemporalType.DATE)
    @Column(name="dateResr", length=0)
    public Date getDateResr() {
        return this.dateResr;
    }
    
    public void setDateResr(Date dateResr) {
        this.dateResr = dateResr;
    }

    
    @Column(name="nbNuits")
    public Integer getNbNuits() {
        return this.nbNuits;
    }
    
    public void setNbNuits(Integer nbNuits) {
        this.nbNuits = nbNuits;
    }




}


